database:
  url: jdbc:mysql://localhost:3306/studies
  username: ${DB_USER}
  password: ${DB_PASSWORD}
  driver: com.mysql.cj.jdbc.Driver

api:
  apod: https://api.nasa.gov/planetary/apod?api_key=${KEY}
